Helper function to enable bucketing
tianyu-l/pytorch_intern24 pull request #16
Opened 2024-08-12 03:20 UTC by ruisizhang123

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-08-17 01:36 UTC, tianyu-l requested changes
looks much better! had some questions and suggestions

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +                #    tensor_args.append(arg)
pls remove

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +
remove empty line

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +        tensor_args = tensor_args_new
```suggestion
        if process_kernel_seperate:
            tensor_args = [TensorBox(StorageBox(x)) for x in tensor_args]
        else:
            tensor_args = [cls.realize_input(x) for x in tensor_args]
```

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +        example_output = kernel(*new_args, **new_kwargs)
put this back to where it was?

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +            if x.get_name() in V.graph.constants:
is this modification needed?

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +            elif x.get_name() in V.graph.torchbind_constants:
ditto

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +        if not isinstance(V.current_node, NullHandler):
it'd be great if you could add comments, e.g. what happens when `isinstance(V.current_node, NullHandler)` and why that's needed for the following works.

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +                if not isinstance(V.current_node, NullHandler):
same here

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +            if self.op_overload == torch.ops.fsdp.chunk_cat.default:
why AG copy-in is missing? I wonder if it causes the memory regression bug.

2024-08-17 01:36 UTC, tianyu-l commented on torch/_inductor/ir.py
> +                and inputs.op_overload == torch.ops.fsdp.chunk_cat.default
ditto: why AG copy-in is missing

2024-08-17 01:36 UTC, tianyu-l commented on torch/distributed/_composable/fsdp/_fsdp_collectives.py
> +        )
we can reuse the code here

2024-08-17 01:36 UTC, tianyu-l commented on torch/distributed/_composable/fsdp/_fsdp_collectives.py
> +        chunk_cat_out = chunk_cat_out.view(world_size, -1)
why this variable is not used anymore?

2024-08-17 01:56 UTC, tianyu-l commented on torch/_inductor/ir.py
> +                process_kernel_seperate = True
in general I wonder what if these ops are from FSDP2 rather than Simple FSDP -- what would it cause?

2024-08-21 00:22 UTC, tianyu-l approved these changes
please
1. comment in the PR where I raised questions, in particular the changes you inherited from Will -- can you link to the PR he had?
2. `process_kernel_separate` only when `simplefsdp` is applied. Not sure what's the best way to do this, e.g. we can do it when `torch._inductor.simplefsdp.enable_bucket = True` (but you may need to move the definition to this PR).

2024-08-31 17:52 UTC, ruisizhang123 commented
> please
> 
> 1. comment in the PR where I raised questions, in particular the changes you inherited from Will -- can you link to the PR he had?

The diffs is https://gist.github.com/yf225/e2b2d424f190050dda92dde1ef63e408.

> 2. `process_kernel_separate` only when `simplefsdp` is applied. Not sure what's the best way to do this, e.g. we can do it when `torch._inductor.simplefsdp.enable_bucket = True` (but you may need to move the definition to this PR).

Moving the config to this pr seems to be the easiest way to me. I just updated

2024-08-31 18:09 UTC, merged